version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: timerDatabase
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: timer_database
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - timer

  storitevDeljenje:
    container_name: timerContainer
    image: ggg_project-storitevtimer
    build: .
    depends_on:
      - postgres
    ports:
      - "8088:8080"
    networks:
      - timer

volumes:
  postgres_data:

networks:
  timer:
#    driver: bridge