version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: obvestilaDatabase
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: timer_obvestila
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - obvestila

  storitevDeljenje:
    container_name: obvestilaContainer
    image: ggg_project-storitevobvestila
    build: .
    depends_on:
      - postgres
    ports:
      - "8090:8080"
    networks:
      - timer

volumes:
  postgres_data:

networks:
  obvestila:
#    driver: bridge
