kumuluzee:
  name: storitevUporabniki
  version: 1.0.0
  env:
    name: dev
  cors:
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Origin: "http://localhost:4200"  # Allow requests from Angular frontend
    Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers: "Content-Type, Authorization, X-Requested-With"
  #datasources:
  #  - jndi-name: jdbc/GoalGetterGroupDS
  #    connection-url: jdbc:postgresql://localhost:5432/goalgettergroup
  #    username: goalgettergroup
  #    password: gggpostgres
  #    max-pool-size: 20
#  server:
#    port: 8080

 # health:
 #   checks:
 #     data-source-health-check:
 #       type: liveness
 #       jndi-name: jdbc/GoalGetterGroupDS
 # rest-client:
 #   registrations:
 #     - class: priporocilni-sistem-api
 #       url: http://localhost:8081/v1
 #       read-timeout: 5000
#integrations:
#  priporocilni-sistem:
#    base-url: http://localhost:8081/v1

#server:
#  port: 8080

#kumuluzee:
#  aplication:
#    name: kartice
