#kumuluzee:
#  name: goalgettergroup
#  version: 1.0.0
 # env:
  #  name: dev
#  datasources:
 #   - jndi-name: jdbc/BelezenjeUrDS
  #    connection-url: jdbc:postgresql://localhost:5432/belezenje
   #   username: postgres
    #  password: postgres
     # max-pool-size: 20
#  health:
 #   checks:
  #    data-source-health-check:
   #     type: liveness
    #    jndi-name: jdbc/BelezenjeUrDS
#  rest-client:
#    registrations:
#      - class: priporocilni-sistem-api
#        url: http://localhost:8080/v1
#        read-timeout: 5000
#integrations:
#  priporocilni-sistem:
#    base-url: http://localhost:8080/v1